# Generated by Django 3.1.7 on 2021-06-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessorizing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('accessory', models.CharField(choices=[('S', 'Shoes'), ('J', 'Jewellery'), ('H', 'Headwear'), ('B', 'Bag')], default='S', max_length=250)),
                ('clothe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.clothe')),
            ],
        ),
    ]
