# Generated by Django 3.1.7 on 2021-06-26 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210625_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothe',
            old_name='product',
            new_name='productcat',
        ),
    ]
